// using-angular/src/app/form/form.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.scss'],
})
export class FormComponent {
  password: string = '';
  inputType: string = 'password';
  visibilityPng: string = '../../assets/show.png';
  indicators = {
    leftBar: '',
    mediumBar: '',
    rightBar: '',
  };

  public toggleVisibility() {
    if (this.inputType === 'password') {
      this.inputType = 'text';
      this.visibilityPng = '../../assets/hide.png';
    } else {
      this.inputType = 'password';
      this.visibilityPng = '../../assets/show.png';
    }
  }
  public passwordHandler() {
    const hasNumbers = /\d/.test(this.password);
    const hasSymbols = /\W/.test(this.password);
    const hasChars = /[a-zA-Z]+/g.test(this.password);
    const twoOfThree =
      (hasChars && hasSymbols && !hasNumbers) ||
      (hasChars && hasNumbers && !hasSymbols) ||
      (hasNumbers && hasSymbols && !hasChars);
    const threOfThree = hasChars && hasSymbols && hasNumbers;
    if (this.password.length === 0) {
      this.indicators = {
        leftBar: '',
        mediumBar: '',
        rightBar: '',
      };
    } else if (this.password.length < 8) {
      this.indicators = {
        leftBar: 'red',
        mediumBar: 'red',
        rightBar: 'red',
      };
    } else {
      this.indicators = {
        leftBar: twoOfThree ? ' yellow' : threOfThree ? 'green' : 'red',
        mediumBar: twoOfThree ? ' yellow' : threOfThree ? ' green' : '',
        rightBar: threOfThree ? ' green' : '',
      };
    }
  }
}

<h1 class="header">How Strong is Your Password?</h1>
<div class="password-wrapper">
    <input class="password-wrapper__input" type={{inputType}} name="password" [(ngModel)]="password"
        (ngModelChange)="passwordHandler()" />
    <div class="password-wrapper__visibility-switch" (click)="toggleVisibility()">
        <img src={{visibilityPng}} alt="">
    </div>
</div>
<div class="indicator-wrapper">
    <div class="indicator">
        <div class="bar" [ngClass]="indicators.leftBar"></div>
        <div class="bar" [ngClass]="indicators.mediumBar"></div>
        <div class="bar" [ngClass]="indicators.rightBar"></div>
    </div>
</div>

// using-react/src/components/Form/Form.tsx
import { useState } from "react"
import PasswordInput from "../PasswordInput/PasswordInput";
import "./Form.css"

function Form(){
    const [indicators, setIndicators] = useState({
        leftBar: "",
        mediumBar: "",
        rightBar: ""
    })
    const checkPassword = (pass:string)=>{
        const hasNumbers = /\d/.test(pass);
        const hasSymbols = /\W/.test(pass);
        const hasChars = /[a-zA-Z]+/g.test(pass);
        const twoOfThree =
        (hasChars && hasSymbols && !hasNumbers) ||
        (hasChars && hasNumbers && !hasSymbols) ||
        (hasNumbers && hasSymbols && !hasChars);
        const threOfThree= hasChars && hasSymbols && hasNumbers;
        if (pass.length === 0){
            setIndicators({
                leftBar: "",
                mediumBar: "",
                rightBar: ""
            })
        } else if (pass.length < 8){
            setIndicators({
                leftBar: " red",
                mediumBar: " red",
                rightBar: " red"
            })
        } else {
            setIndicators({
                leftBar: twoOfThree ? ' yellow' : threOfThree ? ' green' : ' red',
                mediumBar: twoOfThree ? ' yellow' : threOfThree ? ' green' : '',
                rightBar: threOfThree ? ' green' : '',
            })
        }
    }
    return (
    <div className="form">
        <h1 className="header">How Strong is Your Password?</h1>
        <PasswordInput verify={checkPassword}/>
        <div className="indicator-wrapper">
            <div className="indicator">
                <div className={`bar${indicators.leftBar}`}></div>
                <div className={`bar${indicators.mediumBar}`}></div>
                <div className={`bar${indicators.rightBar}`}></div>
            </div>
        </div>
    </div>)
}
export default Form
